// swift-tools-version:6.0
// Package.swift
// The build manifest: every compiled source file is listed below by name, in load order by area.
// Exists so tools/check-project.sh can prove that nothing on disk is left out of the build.
// Defines: the OpenTaskbar executable and the PrivateAPI module
// Notes: docs/notes/app/Package.swift.md
import PackageDescription

let appSources = [
    "App/AppDelegate.swift",
    "App/LaunchChecks.swift",
    "App/Log.swift",
    "App/LoginItem.swift",
    "App/ModuleHost.swift",
    "App/Permissions.swift",
    "App/PermissionsSetup.swift",
    "App/PermissionsSetupView.swift",
    "App/Updater.swift",
    "App/main.swift",
    "Settings/BarSettings.swift",
    "Settings/ClockPreference.swift",
    "Settings/HammerspoonImporter.swift",
    "Settings/SettingsBackup.swift",
    "Settings/SettingsBackupTab.swift",
    "Settings/SettingsBarTab.swift",
    "Settings/SettingsControls.swift",
    "Settings/SettingsInputTab.swift",
    "Settings/SettingsItemsTab.swift",
    "Settings/SettingsModel.swift",
    "Settings/SettingsStartTab.swift",
    "Settings/SettingsStore.swift",
    "Settings/SettingsWindow.swift",
    "Settings/StartIconStore.swift",
    "Drawing/BarGlyphs.swift",
    "Drawing/BarPalette.swift",
    "Drawing/GlyphPen.swift",
    "Drawing/TrayGlyphs.swift",
    "Bar/BarAutoHide.swift",
    "Bar/BarBackground.swift",
    "Bar/BarClickActions.swift",
    "Bar/BarController.swift",
    "Bar/BarLayout.swift",
    "Bar/BarLifecycle.swift",
    "Bar/BarModel.swift",
    "Bar/BarPanel.swift",
    "Bar/BarRenderer.swift",
    "Bar/BarResize.swift",
    "Bar/BarRightClickActions.swift",
    "Bar/BarRightEnd.swift",
    "Bar/BarView.swift",
    "Bar/TaskbarMetrics.swift",
    "Bar/TrayCells.swift",
    "Bar/TrayDrag.swift",
    "Launchers/BarDropTarget.swift",
    "Launchers/LauncherHop.swift",
    "Launchers/LauncherReorder.swift",
    "Launchers/PinnedStore.swift",
    "Windows/AXActor.swift",
    "Windows/WindowActions.swift",
    "Windows/WindowList.swift",
    "Windows/WindowObserver.swift",
    "Windows/WindowPreview.swift",
    "Menus/AppMenuReader.swift",
    "Menus/BarItemMenus.swift",
    "Menus/DockMenuReader.swift",
    "Menus/LauncherContextMenu.swift",
    "Menus/MenuEntry.swift",
    "Menus/StartContextMenu.swift",
    "Menus/UpwardMenu.swift",
    "Start/AppCatalog.swift",
    "Start/StartKeyTap.swift",
    "Start/StartPanel.swift",
    "Start/StartPanelView.swift",
    "Tray/AudioControl.swift",
    "Tray/Battery.swift",
    "Tray/ControlCenterReader.swift",
    "Tray/CoreAudio.swift",
    "Tray/DisplayBrightness.swift",
    "Tray/EnergyUsage.swift",
    "Tray/KeyboardBacklight.swift",
    "Tray/LowPowerMode.swift",
    "Tray/SpotlightLauncher.swift",
    "Tray/StatusItemGlyphs.swift",
    "Tray/StatusItemMirror.swift",
    "Tray/TrayMenus.swift",
    "Tray/TrayOrder.swift",
    "Tray/WiFi.swift",
    "Tray/WiFiNetworks.swift",
    "Panels/BarTooltip.swift",
    "Panels/BatteryPanel.swift",
    "Panels/BatteryPanelView.swift",
    "Panels/CalendarPanel.swift",
    "Panels/FlashAlert.swift",
    "Panels/FlyoutStyle.swift",
    "Panels/PopupPanel.swift",
    "Panels/ScreenRecorder.swift",
    "Panels/SliderPanel.swift",
    "Panels/ToolsPanel.swift",
    "Panels/TrayOverflowPanel.swift",
    "Panels/WiFiPanel.swift",
    "Panels/WiFiPanelView.swift",
    "Power/PowerActions.swift",
    "Input/ChromiumAccessibility.swift",
    "Input/CtrlClickLink.swift",
    "Input/DocumentJumpKeys.swift",
    "Input/FocusedText.swift",
    "Input/HomeEndKeys.swift",
    "Input/HotKeyCenter.swift",
    "Input/HotKeyModule.swift",
    "Input/KeySender.swift",
    "Input/MicMuteKey.swift",
    "Input/TerminalPaste.swift",
    "WindowBehavior/CloseQuitsApp.swift",
    "WindowBehavior/WindowSnapping.swift",
]

let testSources = [
    "BarLayoutTests.swift",
    "BarSnapshotTests.swift",
    "PanelSnapshotTests.swift",
    "TestInputs.swift",
    "StatusGlyphTests.swift",
    "TrayOrderTests.swift",
]

let package = Package(
    name: "OpenTaskbar",
    platforms: [.macOS(.v15)],
    dependencies: [
        .package(url: "https://github.com/sparkle-project/Sparkle", exact: "2.9.6"),
    ],
    targets: [
        .target(
            name: "PrivateAPI",
            path: "Sources/PrivateAPI",
            sources: ["PrivateAPI.m"],
            publicHeadersPath: "include"
        ),
        .executableTarget(
            name: "OpenTaskbar",
            dependencies: ["PrivateAPI", .product(name: "Sparkle", package: "Sparkle")],
            path: "Sources/OpenTaskbar",
            sources: appSources,
            linkerSettings: [
                .unsafeFlags(["-F/System/Library/PrivateFrameworks",
                              "-framework", "DisplayServices",
                              "-framework", "CoreBrightness",
                              "-Xlinker", "-rpath", "-Xlinker", "@executable_path/../Frameworks"]),
                .linkedFramework("ScreenCaptureKit"),
                .linkedFramework("CoreWLAN"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("IOKit"),
                .linkedFramework("ServiceManagement"),
                .linkedFramework("Carbon"),
            ]
        ),
        .testTarget(
            name: "OpenTaskbarTests",
            dependencies: ["OpenTaskbar"],
            path: "Tests/OpenTaskbarTests",
            sources: testSources
        ),
    ]
)
